name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy bot
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - id: adding_bot_env
          run: echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env
        - id: adding_deta_env
          run: echo DETA_KEY=${{ secrets.DETA_KEY }} >> .env
        - id: stop_app
          run: flyctl m stop
        - id: deploy
          run: flyctl deploy --remote-only --detach
