name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy bot
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - id: secrets
          run: flyctl secrets set BOT_TOKEN=${{ secrets.BOT_TOKEN }} DETA_KEY=${{ secrets.DETA_KEY }} --detach
        - id: deploy
          run: flyctl deploy --remote-only --detach
