name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy bot
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
      steps:
        - id: add .env
          run: echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} > .env
          run: echo DETA_KEY=${{ secrets.DETA_KEY }} >> .env
        - id: deploy
          run: flyctl deploy --remote-only
